### ISSUE TITLE
Use w/o Gatsby / suggestions to support MDX@2

### ISSUE THREAD

**Issue by wooorm** [florianeckerstorfer/gatsby-remark-a11y-emoji#66]
Hi! I’m coming here as the maintainer of remark et al, and would like to see a standalone project, for example so that it can be used directly with remark, but also for example with [Next](https://nextjs.org) or [MDSveX](https://github.com/pngwn/MDsveX).
It seems like there’s only a small layer of Gatsby-specific code here?

For the remark part, there are certain Gatsby-esque things in this project, such as using raw HTML strings: https://github.com/florianeckerstorfer/gatsby-remark-a11y-emoji/blob/a7cd05ce41d2399bac49303757dc53f54c9d20e8/src/index.js#L14
That works fine if you’re indeed going to make HTML, and Gatsby (and MDX@1) are doing some magic there, but with MDX@2 we’re going remove it in favor of an AST: [hast](https://github.com/syntax-tree/hast) ([rehype](https://github.com/rehypejs/rehype)) (which the other stuff made on remark already supports).

Is this of interest?

I spent some time thinking about how this plugin could work, and had fun, so here’s a working one that also supports skin tones 😅 https://codesandbox.io/s/remark-rehype-debug-forked-zs711?file=/src/index.js

**Comment by florianeckerstorfer** [comment]
@wooorm The reason why this plugin is Gatsby-specific is also how Gatsby invokes Remark plugins. At least at the time I was writing it there were some custom stuff passed down to plugins in Gatsby. However, I have created a non-Gatsby variant of the plugin as well when I switched my personal website from Gatsby to Eleventy: https://github.com/florianeckerstorfer/remark-a11y-emoji

**Comment by wooorm** [comment]
> At least at the time I was writing it there were some custom stuff passed down to plugins in Gatsby

What information does this plugin depend on? 🤔

> I have created a non-Gatsby variant of the plugin as well when I switched my personal website from Gatsby to Eleventy: https://github.com/florianeckerstorfer/remark-a11y-emoji (which already supports skintones).

Nice! Well, indeed, the main take-away is: https://codesandbox.io/s/remark-rehype-debug-forked-zs711?file=/src/index.js:858-1180

**Comment by florianeckerstorfer** [comment]
@wooorm I'm happy to report that I implemented the plugin using an AST in https://github.com/florianeckerstorfer/remark-a11y-emoji/pull/19

Regarding the Gatsby plugin, the problem is that normally a Remark plugin receives as first argument the AST, but Gatsby passed an object. (I'm pretty sure [this is the line](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/extend-node-type.js#L217) where it happens).

I could check in remark-a11y-emoji if the first argument given to the plugin is an AST or an object that contains a property `markdownAST`, then I would no longer need to maintain two separate plugins.

**Comment by wooorm** [comment]
Awesome!!

For Gatsby, could you use this to wrap the “vanilla” remark plugin and make a “gatsby” remark plugin? https://github.com/kevin940726/to-gatsby-remark-plugin

**Comment by florianeckerstorfer** [comment]
This is now implemented in https://github.com/florianeckerstorfer/remark-a11y-emoji
